version: 1

dependency:
  failureMode: soft
  runtimes:
    - language: node
      install: "pnpm install --frozen-lockfile"

preview:
  instances:
    - name: app
      command: "pnpm dev -- --port {{PORT}}"
      workdir: "."
      env:
        PUBLIC_ORIGIN: "http://127.0.0.1:{{PORT}}"